FROM python:3.11

RUN mkdir /app
RUN mkdir -p /data
COPY . /app
WORKDIR /app
RUN python -m pip install -r requirements.txt

# Ensure the data directory exists and is writable
RUN chmod 777 /data

# Environment variables to prevent flask from reloading
ENV FLASK_DEBUG=0
ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1

# Use python directly instead of flask run to allow for Kademlia DHT
CMD ["python", "node_server.py", "--host", "0.0.0.0", "--port", "8003"]